### ISSUE TITLE
Feature request: hide header

### ISSUE THREAD

**Issue by jlavric** [abhishekjain12/ngx-time-scheduler#16]
Hi!
I have just found this project and it is very promising and super easy to use. Is there a way to hide header and all previous and next and period buttons?
Thnx,
Janez

**Comment by vini-mehta** [comment]
Hi, 
I have the same issue where I am not able to customize the header part of the scheduler according to my requirement.
It would be really helpful the scheduler is more customizable.

Thanks,
Vini

**Comment by abhishekjain12** [comment]
Added in v2.0.0
