### ISSUE TITLE
minRowHeight not defined

### ISSUE THREAD

**Issue by daydraze** [abhishekjain12/ngx-time-scheduler#7]
When asigning items directly, 35 objects or more make scheduler crash on init. 

![image](https://user-images.githubusercontent.com/26826240/80503764-a07c5000-8972-11ea-8fa0-a358556531d7.png)

**Comment by daydraze** [comment]
Found out what it was, when the id of the section is not following order, (1,2,3,4,5,6) but like (1,2,3,56,142) the scheduler will crash because it kan not find element (56 - 1).

![image](https://user-images.githubusercontent.com/26826240/80584357-d6bcdc80-8a11-11ea-9b26-ea63fe9bea85.png)

(added try catch for debug)

**Comment by abhishek-thesunflowerlab** [comment]
@daydraze Noted the issue. Working on the fix.

**Comment by abhishekjain12** [comment]
@daydraze Noted the issue. Working on the fix.

**Comment by abhishekjain12** [comment]
@daydraze Fixed in v1.4.0
